model = "gpt-5.6-sol"
model_reasoning_effort = "medium"
web_search = "live"
personality = "none"
suppress_unstable_features_warning = true
approval_policy = "never"
sandbox_mode = "danger-full-access"
commit_attribution = ""
plan_mode_reasoning_effort = "high"
approvals_reviewer = "user"

[tui]
status_line = [
    "current-dir",
    "git-branch",
    "model-with-reasoning",
    "five-hour-limit",
    "weekly-limit",
    "context-remaining",
    "context-window-size",
]
notifications = true
notification_method = "auto"
notification_condition = "always"

[features]
collaboration_modes = true
unified_exec = true
shell_snapshot = true
powershell_utf8 = true
steer = true
personality = true
multi_agent = true
prevent_idle_sleep = true
apps = false
guardian_approval = true
goals = true
terminal_resize_reflow = true
mentions_v2 = true
js_repl = false

[projects."/Users/adityasharma/Projects/Digests/Digests-Swift"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/figma-console-mcp"]
trust_level = "trusted"

[projects."/"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/dotfiles"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/tasque"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/Digests/digests-api"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/Digests-Swift"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/sysadmin"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/book-recos"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/making-with-ai"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/nova-shell"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/gpui-component"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/ansible"]
trust_level = "trusted"

[projects."/Users/adityasharma"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/roci"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/notes"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/PersonalAssistant"]
trust_level = "trusted"

[projects.'C:\Users\adityasharma\Projects\agent-replay']
trust_level = "trusted"

[projects.'C:\Users\adityasharma\Projects\session-replay']
trust_level = "trusted"

[projects."/home/bumpyclock/Projects/dotfiles"]
trust_level = "trusted"

[projects."/home/bumpyclock/sysadmin"]
trust_level = "trusted"

[projects."/Users/adityasharma/.codex"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/code-tools-mcp"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/intentOS"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/Blender-Wes"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/gpui"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/agent-term"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/Andromeda"]
trust_level = "trusted"

[projects."/Users/adityasharma/Documents/Codex/2026-05-01/what-is-immediate-mode-ui-library"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/digests-api"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/Gurukul/SchoolWeb"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/Digests"]
trust_level = "trusted"

[projects."/Users/adityasharma/.agents"]
trust_level = "trusted"

[projects.'c:\users\adityasharma\projects\nova-shell']
trust_level = "trusted"

[projects."/Volumes/Portkey/Projects/gaussian-splats/proto"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/schoolweb"]
trust_level = "trusted"

[mcp_servers.exa-search]
url = "https://mcp.exa.ai/mcp"
startup_timeout_sec = 20

[mcp_servers.exa-search.http_headers]
x-api-key = "0b3e8d1c-6330-45d9-be1f-0c4d2c0e1989"

[mcp_servers.node_repl]
args = []
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/adityasharma/.codex"
CODEX_HOME = "/Users/adityasharma/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "1491199f46178eb038259aaea144492b8a8ade32bba5d2b4843c94936be551bb,6d25aa7656feac858f3a3bdaea5bcbab0dbfd426c9de8e6931ce90c399ee8e4f"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = "Control desktop apps on macOS through Computer Use."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.707.41301"
SKY_CUA_SERVICE_PATH = "/Users/adityasharma/.codex/plugins/cache/openai-bundled/computer-use/1.0.1000366/Codex Computer Use.app"
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex"

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = ["mcp"]
cwd = "."
enabled = false

[mcp_servers.rive]
enabled = true
url = "http://127.0.0.1:9791/mcp"

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[plugins."google-calendar@openai-curated"]
enabled = false

[plugins."gmail@openai-curated"]
enabled = false

[plugins."github@openai-curated"]
enabled = true

[plugins."google-drive@openai-curated"]
enabled = false

[plugins."build-ios-apps@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = false

[plugins."spreadsheets@openai-primary-runtime"]
enabled = false

[plugins."presentations@openai-primary-runtime"]
enabled = false

[plugins."browser-use@openai-bundled"]
enabled = true

[plugins."linear@openai-curated"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."warp@codex-warp"]
enabled = true

[plugins."sites@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."swift-lsp@claude-plugins-official"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[marketplaces.openai-bundled]
last_updated = "2026-07-12T04:59:22Z"
source_type = "local"
source = "/Users/adityasharma/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-12T05:40:19Z"
source_type = "local"
source = "/Users/adityasharma/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[marketplaces.claude-plugins-official]
last_updated = "2026-07-12T04:59:18Z"
last_revision = "1afdc0d238b61673e8f2bb57622e73641000bb75"
source_type = "git"
source = "https://github.com/anthropics/claude-plugins-official.git"

[desktop]
reviewDelivery = "detached"
keepRemoteControlAwakeWhilePluggedIn = true
conversationDetailMode = "STEPS_COMMANDS"
sansFontSize = 14
codeFontSize = 13
ambient-suggestions-enabled = true
appearanceLightCodeThemeId = "absolutely"
selected-avatar-id = "null-signal"
followUpQueueMode = "queue"
preventSleepWhileRunning = false
dock-icon-preference = "codex-system"

[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
AUTO_TOOL_SEARCH = "auto:5"
CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS = "1"
