model = "gpt-5.5"
model_instructions_file = "~/.codex/model-instructions.md"
model_reasoning_effort = "high"
web_search = "live"
personality = "none"
suppress_unstable_features_warning = true
tui.status_line = ["current-dir", "git-branch","model-with-reasoning","five-hour-limit", "weekly-limit", "context-remaining", "context-window-size"]
tui.notifications = true
tui.notification_method = "auto"
tui.notification_condition = "always"
approval_policy = "never"
sandbox_mode = "danger-full-access"
model_context_window = 750000
model_auto_compact_token_limit = 650000
commit_attribution = ""
plan_mode_reasoning_effort = "high"
approvals_reviewer = "user"



service_tier = "default"

notify = ["/Users/adityasharma/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended", "--previous-notify", "[\"C:\\\\Users\\\\adityasharma\\\\.codex\\\\plugins\\\\cache\\\\openai-bundled\\\\computer-use\\\\26.602.40724\\\\node_modules\\\\@oai\\\\sky\\\\bin\\\\windows\\\\codex-computer-use.exe\",\"turn-ended\",\"--previous-notify\",\"[\\\"\\/Users\\/adityasharma\\/.codex\\/computer-use\\/Codex Computer Use.app\\/Contents\\/SharedSupport\\/SkyComputerUseClient.app\\/Contents\\/MacOS\\/SkyComputerUseClient\\\",\\\"turn-ended\\\"]\"]"]

[tui.model_availability_nux]
"gpt-5.5" = 4

[features]
collaboration_modes = true
unified_exec = true
shell_snapshot = true
powershell_utf8 = true
steer = true
personality = true
multi_agent = true
prevent_idle_sleep = true
apps = false
guardian_approval = true
goals = true
terminal_resize_reflow = true
mentions_v2 = true
js_repl = false

[notice]
fast_default_opt_out = true
hide_rate_limit_model_nudge = true



[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
"gpt-5.2" = "gpt-5.2-codex"
"gpt-5.2-codex" = "gpt-5.3-codex"
"gpt-5.3-codex" = "gpt-5.5"


[projects."C:\\Users\\adityasharma\\Projects\\code-tools-mcp"]
trust_level = "trusted"

[projects."C:\\Users\\adityasharma\\Projects\\Digests-Windows"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/Digests/Digests-Swift"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/figma-console-mcp"]
trust_level = "trusted"

[projects."/"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/dotfiles"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/tasque"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/Digests/digests-api"]
trust_level = "trusted"

[projects.'\\?\C:\Users\adityasharma\Projects\Wallpaper_splat']
trust_level = "trusted"

[projects.'\\?\C:\Users\adityasharma\Projects\dotfiles']
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/Digests-Swift"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/sysadmin"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/book-recos"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/making-with-ai"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/nova-shell"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/gpui-component"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/ansible"]
trust_level = "trusted"

[projects."/Users/adityasharma"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/roci"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/notes"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/PersonalAssistant"]
trust_level = "trusted"

[projects.'C:\Users\adityasharma\Projects\agent-replay']
trust_level = "trusted"

[projects.'C:\Users\adityasharma\Projects\session-replay']
trust_level = "trusted"

[projects."/home/bumpyclock/Projects/dotfiles"]
trust_level = "trusted"

[projects."/home/bumpyclock/sysadmin"]
trust_level = "trusted"

[projects."/Users/adityasharma/.codex"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/code-tools-mcp"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/intentOS"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/Blender-Wes"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/gpui"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/agent-term"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/Andromeda"]
trust_level = "trusted"

[projects."/Users/adityasharma/Documents/Codex/2026-05-01/what-is-immediate-mode-ui-library"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/digests-api"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/Gurukul/SchoolWeb"]
trust_level = "trusted"

[projects."/Users/adityasharma/Projects/Digests"]
trust_level = "trusted"

[projects."/Users/adityasharma/.agents"]
trust_level = "trusted"

[projects.'c:\users\adityasharma\projects\nova-shell']
trust_level = "trusted"

[projects."/Volumes/Portkey/Projects/gaussian-splats/proto"]
trust_level = "trusted"


#Agents configuration
[agents]
max_threads = 24

## END AGENT CONFIG

[mcp_servers.exa-search]
url = "https://mcp.exa.ai/mcp"
startup_timeout_sec = 20
http_headers = { "x-api-key" = "0b3e8d1c-6330-45d9-be1f-0c4d2c0e1989" }

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/adityasharma/.codex"
CODEX_HOME = "/Users/adityasharma/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "60e4902788f207f88fd09344dfeafe07769488bdb2924bbb12b322c3b9d2b999"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.623.101652"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

# [mcp_servers."playwriter"]
# command = "bunx"
# args = [ "playwriter@latest" ]
# startup_timeout_sec = 40
# env = { PLAYWRITER_AUTO_ENABLE="1" }

[windows]
sandbox = "elevated"

[plugins."google-calendar@openai-curated"]
enabled = false

[plugins."gmail@openai-curated"]
enabled = false

[plugins."github@openai-curated"]
enabled = true

[plugins."google-drive@openai-curated"]
enabled = false

[plugins."build-ios-apps@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = false

[plugins."spreadsheets@openai-primary-runtime"]
enabled = false

[plugins."presentations@openai-primary-runtime"]
enabled = false

[plugins."browser-use@openai-bundled"]
enabled = true

[plugins."linear@openai-curated"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."warp@codex-warp"]
enabled = true

[[skills.config]]
path = "/Users/adityasharma/Projects/dotfiles/skills/1password/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/.codex/plugins/cache/openai-bundled/browser-use/0.1.0-alpha1/skills/browser/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/.codex/plugins/cache/openai-primary-runtime/documents/26.430.10722/skills/documents/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/Projects/dotfiles/skills/figma/figma-code-connect/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/Projects/dotfiles/skills/figma/figma-create-design-system-rules/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/Projects/dotfiles/skills/figma/figma-create-new-file/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/Projects/dotfiles/skills/figma/figma-generate-design/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/Projects/dotfiles/skills/figma/figma-generate-library/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/Projects/dotfiles/skills/figma/figma-implement-design/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/Projects/dotfiles/skills/figma/figma-use/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/Projects/dotfiles/skills/opentui/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/Projects/dotfiles/skills/peeku-windows/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/Projects/dotfiles/skills/playwriter/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/Projects/dotfiles/skills/shadcn/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/.codex/plugins/cache/openai-primary-runtime/spreadsheets/26.430.10722/skills/spreadsheets/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/Projects/dotfiles/skills/winui3-csharp-app/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/Projects/dotfiles/skills/.system/plugin-creator/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/Projects/dotfiles/skills/.system/skill-creator/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/adityasharma/Projects/dotfiles/skills/.system/skill-installer/SKILL.md"
enabled = false

[marketplaces.openai-bundled]
last_updated = "2026-07-06T16:03:40Z"
source_type = "local"
source = "/Users/adityasharma/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-01T07:14:21Z"
source_type = "local"
source = "/Users/adityasharma/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[marketplaces.claude-plugins-official]
last_updated = "2026-07-06T16:13:59Z"
last_revision = "01c4d1bc1138666989d4b8a581b3ead249dcf6d7"
source_type = "git"
source = "https://github.com/anthropics/claude-plugins-official.git"

[marketplaces.codex-warp]
last_updated = "2026-07-06T04:21:17Z"
last_revision = "f11334dc715d48f07d133db6046895cb45f4accb"
source_type = "git"
source = "https://github.com/warpdotdev/codex-warp.git"

[desktop]
reviewDelivery = "detached"
keepRemoteControlAwakeWhilePluggedIn = true
conversationDetailMode = "STEPS_PROSE"
sansFontSize = 14
codeFontSize = 13
ambient-suggestions-enabled = true
appearanceLightCodeThemeId = "absolutely"
selected-avatar-id = "null-signal"
followUpQueueMode = "queue"
preventSleepWhileRunning = false

[desktop.appearanceLightChromeTheme]
accent = "#cc7d5e"
contrast = 45
ink = "#2d2d2b"
opaqueWindows = false
surface = "#f9f9f7"

[desktop.appearanceLightChromeTheme.fonts]

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#00c853"
diffRemoved = "#ff5f38"
skill = "#cc7d5e"

[desktop.open-in-target-preferences]
global = "zed"

[desktop.open-in-target-preferences.perPath]
"/Users/adityasharma/Projects/gpui" = "zed"

# [mcp_servers.openaiDeveloperDocs]
# url = "https://developers.openai.com/mcp"
#
